name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Bun v1.1.24
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.24'

      # 3. Install dependencies using Bun
      - name: Install dependencies
        run: bun install --frozen-lockfile


      # 4. Deploy your database migrations
      - name: Apply database migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: bun db:migrate:deploy
